In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import kaggle
kaggle.api.authenticate()
kaggle.api.dataset_download_files(
    'salman1127/fish-market-dataset',
    path ='.',
    unzip = True
)

Dataset URL: https://www.kaggle.com/datasets/salman1127/fish-market-dataset

In [4]:
df  = pd.read_csv(r'POLYNOMIAL_REGRESSION\Fishers maket.csv')
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [11]:
df['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [12]:
from ydata_profiling import ProfileReport

prof = ProfileReport(df)

prof.to_file(output_file='output.html')

C:\Users\NIKHI\AppData\Local\Temp\ipykernel_19448\1333572948.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:00<00:00, 26.74it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [13]:
#vif
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

In [17]:
X= df.drop(columns='Weight')

In [18]:
X

    Species  Length1  Length2  Length3   Height   Width
0     Bream     23.2     25.4     30.0  11.5200  4.0200
1     Bream     24.0     26.3     31.2  12.4800  4.3056
2     Bream     23.9     26.5     31.1  12.3778  4.6961
3     Bream     26.3     29.0     33.5  12.7300  4.4555
4     Bream     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154   Smelt     11.5     12.2     13.4   2.0904  1.3936
155   Smelt     11.7     12.4     13.5   2.4300  1.2690
156   Smelt     12.1     13.0     13.8   2.2770  1.2558
157   Smelt     13.2     14.3     15.2   2.8728  2.0672
158   Smelt     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [31]:
y = df['Weight']

In [32]:
y

0      242.0
1      290.0
2      340.0
3      363.0
4      430.0
       ...
154     12.2
155     13.4
156     12.2
157     19.7
158     19.9
Name: Weight, Length: 159, dtype: float64

In [33]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train , y_test = train_test_split(X, y,
                                                     test_size=0.2,
                                                     random_state=42)

In [34]:
X_train.shape

(127, 6)

In [35]:
y_train.shape

(127,)

In [38]:
X_vif = pd.get_dummies(X_train, drop_first = True)

In [39]:
X_with_constant = add_constant(X_vif)

In [40]:
vif_data = pd.DataFrame()
vif_data["Feature"] = X_with_constant.columns
vif_data["VIF"] = [
    variance_inflation_factor(X_with_constant.values, i)
    for i in range(X_with_constant.shape[1])
]

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''